src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DLN__c</fullName>
        <encrypted>true</encrypted>
        <label>DLN</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <encrypted>true</encrypted>
        <label>SSN</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BasicController.cls
public with sharing class BasicController {


	public List<Contact> contacts {get;set;}

	public BasicController() {

		if (ApexPages.currentPage() != null && ApexPages.currentPage().getParameters().get('reqType') == 'sosl') {

			runSosl();

		} else {

			runSoql();

		}
		
	}

	public void runSoql(){

		contacts = [select Id, FirstName,LastName,Email,Phone, DLN__c, SSN__c from Contact];

	}

	public void runSosl(){

		contacts = (List<Contact>) [FIND '*ba*' IN ALL FIELDS RETURNING Contact(Id,FirstName,LastName,Email,Phone,SSN__c,DLN__c)][0];

	}
}